name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      # Add other branches if you want, e.g.:
      # - staging
      # - your-feature-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # For repo site, this is usually enough
          # If you use custom domain or different branch, configure here
